services:
  db:
    image: mysql:8.0
    container_name: gf2tool-mysql
    ports:
      - "3307:3306" # 포트 포워딩(3307 -> 3306)
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: gf2tool_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql # 데이터 보존을 위한 볼륨 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
volumes:
  mysql_data:
